services:
  - type: web
    name: rick-and-morty-api
    runtime: node
    plan: free
    buildCommand: npx prisma generate && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: DATABASE_URL
      - key: JWT_SECRET
      - key: JWT_EXPIRES_IN
      - key: FRONTEND_URL
      - key: NODE_ENV
        value: production
